config_Service_1 = {'gpon': ["profile bandwidth test maximum 100000"],
                    'gpon-onu1': ["tcont 1 profile test",
                                      "gemport 1 tcont 1",
                                      "service-port 1 gemport 1 user-vlan vlan transparent",
                                      "remote service 1 gem 1 uni veip vlan-mode access pvlan vlan priority 7"],
                    'total':[
                             "bridge 1 protocol rstp-vlan-bridge", 
                             "spanning-tree bridge 1 pathcost method short", 
                             "spanning-tree bridge 1 portfast bpdu-guard",
                             "vlan 111 bridge 1 type customer state enable",
                             "vlan 112 bridge 1 type customer state enable",
                             "vlan 113 bridge 1 type customer state enable",
                             "vlan 114 bridge 1 type customer state enable",
                             "vlan 115 bridge 1 type customer state enable",
                             "vlan 116 bridge 1 type customer state enable",
                             "vlan 117 bridge 1 type customer state enable",
                             "vlan 118 bridge 1 type customer state enable",
                             "vlan 119 bridge 1 type customer state enable",
                             "vlan 220 bridge 1 type customer state enable",
                             "vlan 221 bridge 1 type customer state enable",
                             "vlan 222 bridge 1 type customer state enable"],
                    'gpon-olt1/1':
                            ["no shutdown",
                            "switchport",
                            "bridge-group 1 spanning-tree enable",
                            "storm-control broadcast level 85",
                            "switchport mode trunk",
                            "switchport trunk tag 111-119,220-222"
                            ],
                #     'gpon-olt1/2':
                #            ["no shutdown",
                #             "switchport",
                #             "bridge-group 1 spanning-tree enable",
                #             "storm-control broadcast level 85",
                #             "switchport mode trunk",
                #             "switchport trunk tag 111-119,220-222"
                #             ],
                    'ge1/1':
                            ["max-frame 1650", 
                            "switchport",
                            "bridge-group 1 spanning-tree enable", 
                            "bridge-group 1 spanning-tree enable stp",
                            "switchport mode trunk",
                            "switchport trunk tag 111-119,220-222",
                            "spanning-tree bpdu-filter enable",
                            "speed 1G"]}

#*******************************************************************************   
config_Service_2 = {'gpon': ["profile bandwidth test maximum 100000"],
                    'gpon-onu1': ["tcont 1 profile test",
                                      "gemport 1 tcont 1"],
                    'gpon-onu1_repeat': ["service-port 1 gemport 1 user-vlan vlan transparent",
                                      "remote service 1 gem 1 uni veip vlan-mode access pvlan vlan priority 7"],
                    'total':["bridge 1 protocol rstp-vlan-bridge", 
                             "spanning-tree bridge 1 pathcost method short", 
                             "spanning-tree bridge 1 portfast bpdu-guard",
                             "vlan 111 bridge 1 type customer state enable",
                             "vlan 112 bridge 1 type customer state enable",
                             "vlan 113 bridge 1 type customer state enable",
                             "vlan 114 bridge 1 type customer state enable",
                             "vlan 115 bridge 1 type customer state enable",
                             "vlan 116 bridge 1 type customer state enable",
                             "vlan 117 bridge 1 type customer state enable",
                             "vlan 118 bridge 1 type customer state enable",
                             "vlan 119 bridge 1 type customer state enable",
                             "vlan 220 bridge 1 type customer state enable",
                             "vlan 221 bridge 1 type customer state enable",
                             "vlan 222 bridge 1 type customer state enable"],
                    'gpon-olt1':
                            ["no shutdown",
                            "switchport",
                            "bridge-group 1 spanning-tree enable",
                            "storm-control broadcast level 85",
                            "switchport mode trunk",
                            "switchport trunk tag 111-119,220-222"
                            ],
                    'ge1/1':
                            ["max-frame 1650", 
                            "switchport",
                            "bridge-group 1 spanning-tree enable", 
                            "bridge-group 1 spanning-tree enable stp",
                            "switchport mode trunk",
                            "switchport trunk tag 111-119,220-222",
                            "spanning-tree bpdu-filter enable",
                            "speed 1G"],
                    "ge1/2" :[
                            "speed 1G",
                            "max-frame 1650",
                            "switchport", 
                            "bridge-group 1 spanning-tree enable",
                            "storm-control broadcast level 85",
                            "switchport mode trunk",
                            "switchport trunk tag 117-119,220-222",
                            "spanning-tree bpdu-guard enable"]}        
#****************************************************************************************************
config_Service_3 = {'gpon': ["profile bandwidth test maximum 100000"],
                    'gpon-onu1': ["tcont 1 profile test",
                                      "gemport 1 tcont 1"],
                    'gpon-onu1_repeat': ["service-port 1 gemport 1 user-vlan vlan transparent",
                                      "remote service 1 gem 1 uni veip vlan-mode access pvlan vlan priority 7"],
                    'total':["bridge 1 protocol rstp-vlan-bridge", 
                             "spanning-tree bridge 1 pathcost method short", 
                             "spanning-tree bridge 1 portfast bpdu-guard",
                             "vlan 111 bridge 1 type customer state enable",
                             "vlan 112 bridge 1 type customer state enable",
                             "vlan 113 bridge 1 type customer state enable",
                             "vlan 114 bridge 1 type customer state enable",
                             "vlan 115 bridge 1 type customer state enable",
                             "vlan 11 bridge 1 type service-point-point state enable",
                             "vlan 12 bridge 1 type service-point-point state enable",
                             "vlan 13 bridge 1 type service-point-point state enable",
                             "vlan 14 bridge 1 type service-point-point state enable",
                             "vlan 15 bridge 1 type service-point-point state enable",
                             "registration table reg1 bridge 1 cvlan 111,112,113,114,115 svlan 11,12,13,14,15"],
                    'gpon-olt1/1':
                            ["no shutdown",
                            "switchport",
                            "bridge-group 1 spanning-tree enable"
                            "switchport mode customer-edge-trunk",
                            "switchport QinQ trunk mode C-tagged tag 111-115 egresstag enable",
                            "switchport QinQ registration reg1"
                            ],
                    'ge1/1':
                            ["switchport",
                            "bridge-group 1 spanning-tree enable", 
                            "switchport mode customer-network",
                            "switchport QinQ trunk mode S-tagged tag 11-15",
                            "speed 1G"]}                                                                      